### ISSUE TITLE
Task 1 - HacktoberFest

### ISSUE THREAD

**Issue by Pratham-R** [Developer-Student-Clubs-UBa/hactoberfest2022#475]

**Comment by Pratham-R** [comment]
can you assign me to this issue?

**Comment by ayushgituser** [comment]
Hii! I can do this work with perfection. Please assign me this task

**Comment by Nitish-Kumar789** [comment]
can u give brief intro abt what to dp

**Comment by Arkapro1** [comment]
Hello 👋 , I carefully read the instructions and want to contribute also... Please assign me the task.

**Comment by Aniketmishra0** [comment]
Hello Sir,
Can You assign this issue to me?

**Comment by Nikhil3389** [comment]
Hello Sir,
Can You assign this issue to me?
